# Generated by Django 2.1 on 2018-09-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['county', 'type', 'id']},
        ),
    ]
