# Generated by Django 2.1 on 2018-09-06 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150)),
                ('image', models.URLField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('took_at', models.DateTimeField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploader', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidates', models.ManyToManyField(related_name='board_candidates', to='candidates.Candidates')),
            ],
        ),
    ]
