# Generated by Django 2.1.2 on 2019-09-12 20:52

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('county', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=15)),
                ('road', models.CharField(blank=True, max_length=75)),
                ('took_at', models.DateTimeField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_by', models.UUIDField(editable=False)),
                ('price', models.IntegerField(null=True)),
                ('receipt', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=None, null=True, size=None)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('verified_amount', models.IntegerField(default=0)),
                ('not_board_amount', models.IntegerField(default=0)),
                ('is_board', models.BooleanField(default=False)),
                ('candidates', models.ManyToManyField(related_name='boards', to='candidates.Terms')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=128, null=True)),
                ('is_board', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=0)),
                ('headcount', models.IntegerField(default=None, null=True)),
                ('is_original', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_checks', to='boards.Boards')),
                ('candidates', models.ManyToManyField(related_name='check_candidates', to='candidates.Terms')),
            ],
        ),
    ]
