# Generated by Django 2.1 on 2018-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='uploader',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='address',
        ),
        migrations.AddField(
            model_name='boards',
            name='county',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='boards',
            name='district',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='boards',
            name='road',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='boards',
            name='verified_amount',
            field=models.IntegerField(default=0),
        ),
    ]
