# Generated by Django 2.1.2 on 2019-09-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='uploader_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
