# Generated by Django 2.1.2 on 2019-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boards_uploader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='board_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='party_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boards',
            name='slogan',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='checks',
            name='board_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='checks',
            name='party_icon',
            field=models.BooleanField(default=False),
        ),
    ]
