# Generated by Django 2.1 on 2018-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180907_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='candidates',
            field=models.ManyToManyField(related_name='term_boards', to='candidates.Terms'),
        ),
    ]
