# Generated by Django 2.1 on 2018-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180907_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='boards',
            name='has_price_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boards',
            name='has_receipt_inof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boards',
            name='is_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boards',
            name='candidates',
            field=models.ManyToManyField(related_name='boards', to='candidates.Terms'),
        ),
    ]
