# Generated by Django 2.1 on 2018-09-12 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20180911_1034'),
        ('boards', '0004_auto_20180911_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=15)),
                ('slogan', models.CharField(max_length=128)),
                ('is_board', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_checks', to='boards.Boards')),
                ('candidates', models.ManyToManyField(related_name='check_candidates', to='candidates.Terms')),
            ],
        ),
    ]
