# Generated by Django 2.1 on 2018-09-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='boards',
            name='uploaded_by',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
