# Generated by Django 2.1 on 2018-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180914_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='uploaded_by',
            field=models.UUIDField(editable=False),
        ),
    ]
