# Generated by Django 2.1 on 2018-09-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20180914_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='created_by',
            field=models.UUIDField(editable=False),
        ),
    ]
