# Generated by Django 2.1 on 2018-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20180920_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='county',
        ),
        migrations.RemoveField(
            model_name='checks',
            name='district',
        ),
        migrations.AlterField(
            model_name='checks',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='check_candidates', to='candidates.Terms'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='slogan',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
