# Generated by Django 2.1 on 2018-09-27 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20180927_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checks',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checks',
            name='candidates',
            field=models.ManyToManyField(related_name='check_candidates', to='candidates.Terms'),
        ),
    ]
