# Generated by Django 2.1.2 on 2018-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20180927_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='headcount',
            field=models.IntegerField(default=1),
        ),
    ]
