# Generated by Django 2.1.2 on 2018-10-16 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_checks_headcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='has_receipt_inof',
            new_name='has_receipt_info',
        ),
        migrations.AddField(
            model_name='boards',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='receipt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=None, null=True, size=None),
        ),
    ]
