# Generated by Django 2.1.2 on 2018-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20181016_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='is_original',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='checks',
            name='headcount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
