# Generated by Django 2.1.2 on 2018-10-18 08:03

from django.db import migrations

def make_original_record(apps, schema_editor):
    Boards = apps.get_model('boards', 'Boards')
    Checks = apps.get_model('boards', 'Checks')

    for board in Boards.objects.prefetch_related('candidates'):
        if not Checks.objects.filter(board=board.pk, is_original=True).exists():
            check = Checks(board=board, is_board=True, is_original=True, headcount=board.candidates.count(), created_at=board.uploaded_at, created_by=board.uploaded_by)
            check.save()

            for candidate in board.candidates.all():
                check.candidates.add(candidate)

class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20181018_0416'),
    ]

    operations = [
        migrations.RunPython(make_original_record),
    ]
