# Generated by Django 2.1.2 on 2018-10-29 08:10

from django.db import migrations

def count_not_board_amount(apps, schema_editor):
    Boards = apps.get_model('boards', 'Boards')
    Checks = apps.get_model('boards', 'Checks')

    for check in Checks.objects.filter(type = 2, is_board = False, is_original=False):
        board = Boards.objects.get(pk=check.board.id)
        board.not_board_amount += 1
        board.save()

class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20181029_0758'),
    ]

    operations = [
        migrations.RunPython(count_not_board_amount),
    ]
