# Generated by Django 2.1.2 on 2018-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20181029_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
