# Generated by Django 2.1 on 2018-09-06 09:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Councilors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('former_names', models.CharField(blank=True, max_length=100, null=True)),
                ('identifiers', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilorsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(db_index=True, null=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.TextField(blank=True, db_index=True, null=True)),
                ('in_office', models.BooleanField(db_index=True)),
                ('contact_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('social_media', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('param', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('councilor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='each_terms', to='councilors.Councilors', to_field='uid')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='councilorsdetail',
            unique_together={('councilor', 'election_year')},
        ),
    ]
